name: Deploy to App Engine (disabled)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: fourth-buffer-424217-j3
          workload_identity_provider: projects/584782482619/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-appengine-deployer@fourth-buffer-424217-j3.iam.gserviceaccount.com

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Deploy
        run: gcloud app deploy app.yaml --project=fourth-buffer-424217-j3 --quiet
